/** @type {import('tailwindcss').Config} */

module.exports = {
  mode: "jit",
  content: ["./app/**/*.{js,ts,jsx,tsx}"],
  options: {
    safelist: ["bg-color-1", "bg-color-2", "bg-color-3"],
  },
  theme: {
    extend: {
      fontFamily: {
        corp: ["var(--font-corp)"],
        montserrat: ["Montserrat", "sans-serif"],
        cantarell: ["Cantarell", "sans-serif"],
        roboto: ["Roboto Condensed", "sans-serif"],
        notojp: ["Noto Sans JP", "sans-serif"],
        nova: ["Nova Mono", "sans-serif"],
        fallback: ["Noto Sans JP", "sans-serif"],
      },
      colors: {
        "color-musashi": "#40A5A8",
        "color-bg": "#00558F",
        "color-bg-sns": "#EDEDE2",
        "color-bg-simple-modal": "#3EBFD6",
        "color-c-green": "#0BA500",
        "color-c-yellow": "#FFE100",
        "color-c-light-orange": "#FFA600",
        "color-c-orange": "#F25C00",
        "color-c-red": "#D65633",
        "color-c-pink": "#FE83C4",
        "color-c-puple": "#D633B3",
        "color-c-blue": "#00C4F4",
        "color-c-red": "#D24135",
        "color-white-base": "#FFFFFF",
        "color-black-base": "#000000",
        "color-button": "#FE4000",
        "color-gray": "#EFEFEF",
        "color-beige": "#2F8EA7",
        "color-dark-blue": "#0078AC",
        "color-green-account": "#127021",
        "color-line": "#269BBD",
        "color-base": "#1D284D",
        "color-base-1": "#EFEDE0",
        "color-base-1-light": "#F4F3EC",
        "color-base-1-dark": "#C6BF8E",
        "color-base-1-deep": "#A59B54",
        "color-base-2": "#41A7AA",
        "color-base-light": "#212F67",
        "color-base-title": "#FFDF25",
        "color-error": "#FF4000",
        "color-selected": "#FCC918",
        "color-input-border": "#D7D7D7",
        "color-pickup-field": "#FFE100",
        "color-sidebar-field": "#FF8A15 ",
        "color-category-selected": "#FF4000",
        "color-carousel-selected": "#FF4000",
        "color-multi": "#F85C3A",
        "color-edit": "#3D54A3",
        "color-id": "#6A6A6A",
        "color-like": "#FE3040",
        "color-account": "#F87932",
        "color-support": "#FCC812",
        "color-input-area": "#FFF7EE",
        "color-dashboard-link": "#EDEDE2",
        "color-dashboard-cal-selected": "#FF4000",
        "color-dashboard-cal-today": "#F9DA00",
        "color-dashboard-cal-event": "#00D5FF",
        "color-dashboard-cal-reserve": "#E20012",
        "color-dashboard-ds-event": "#00D5FF",
        "color-dashboard-ds-reserve": "#E20012",
        "color-dashboard-my-ticket-status-completed": "#FF4000",
        "color-dashboard-signature-achievement-selected": "#FFA600",
        "color-account-title": "#ECECEC",
        "color-account-title-font": "#000000",
        "color-ticket-search-fileter": "#FF4000",
        "color-ticket-purchased": "#25AF1C",
        "color-ticket-promotion-cd": "#009932",
        "color-modal-border-upgrade": "#127021",
        "color-modal-border-award-medal": "#FFA600",
        "color-modal-border-ad": "#CCCCCC",
        "color-modal-border-spot-registered": "#FFA600",
        "color-purchase-shipping-selected": "#FFA600",
        "color-print": "#009932",
        "color-certificate-font": "#1A3151",
        "color-certificate-font_2": "#FBAE3C",
        "color-certificate-bg": "#FFE100",
        "color-certificate-border": "#1A3151",
        "color-certificate-border_2": "#FBAE3C",
        "color-certificate-header": "#FFFFFF",
        "color-certificate-main": "#FFFFFF",
        "color-certificate-footer": "#FFFFFF",
        "color-certificate-print": "#E30000",
        "color-kit": "#3EBFD6",
        "color-kit-manual": "#0000BD",
        "color-kit-card-manual-schoomy": "#0000BD",
        "color-kit-setting": "#FEE000",
        "color-kit-card-setting-install": "#FECE07",
        "color-kit-card-programming": "#FECE07",
        "color-kit-card-metaverse": "#DB0000",
        "color-kit-card-challenge": "#DB0000",
        "color-kit-card-setting-bg": "#E8E8DE",
        "color-kit-card-class-bg": "#E8E8DE",
        "color-kit-gear-comment": "#3EBFD6",
        "color-kit-gear-comment-bg": "#D3F0F5",
        "color-kit-gear-edit-publish": "#0BA500",
        "color-kit-gear-edit-publish-light": "#C2FFBD",
        "color-kit-gear-edit-publish-letter": "#11CB07",
        "color-kit-gear-edit-draft": "#666666",
        "color-kit-gear-edit-draft-light": "#EEEEEE",
        "color-kit-gear-edit-draft-letter": "#9CA3AF",
        "color-kit-developer-score": "#D3F0F5",
        "color-kit-manual-release-note-bg": "#CCFFFF",
        "color-kit-manual-release-note-title-bg": "#003399",
        "color-kit-spot-map-registration": "#0BA500",
        "color-kit-spot-map-unregistration": "#8C8C8C",
        "color-kit-spot-map-spot-group-reg": "#FF4000",
        "color-kit-spot-map-spot-group-unreg": "#1771B9",
        "color-spot-news-place": "#00B8E6",
        "color-spot-news-event": "#FF3300",
        "color-achievement-badge-3": "#FFF7DB",
        "color-achievement-badge-2": "#EBEBEB",
        "color-achievement-badge-1": "#FFE7D9",
        "color-achievement-badge-0": "#FFFFFF",
        "color-interim-bg": "#F4AC1E",
        "color-interim-deep-bg": "#F26E30",
        "color-box-list-header-bg": "#f0ffff",
        "color-box-status-active-bg": "#32cd32",
        "color-box-status-in-active-bg": "#808080",
        "color-box-status-in-review-bg": "#ffd700",
        "color-box-status-rejected-bg": "#ffb6c1",
        "color-required": "#EE0000",
      },
      zIndex: {
        100: "100",
      },
      margin: [
        "last",
        {
          "1px": "1px",
          "2px": "2px",
          "3px": "3px",
          "4px": "4px",
          "5px": "5px",
          "6px": "6px",
          "7px": "7px",
          "10px": "10px",
          "20px": "20px",
          "24px": "24px",
          "72px": "72px",
        },
      ],
      padding: {
        "10px": "30px",
        "20px": "20px",
        "45px": "45px",
      },
      width: {
        "20px": "20px",
        "30px": "30px",
        "40px": "40px",
        "60px": "60px",
        "100px": "100px",
        "120px": "120px",
        "150px": "150px",
        "200px": "200px",
        "250px": "250px",
        "300px": "300px",
        "400px": "400px",
        "500px": "500px",
      },
      height: {
        "10px": "10px",
        "20px": "20px",
        "30px": "30px",
        "40px": "40px",
        "50px": "50px",
        "120px": "120px",
        "250px": "250px",
        "300px": "300px",
        "800px": "800px",
      },
      fontSize: {
        xxs: ".625rem",
        "6px": "6px",
        "8px": "8px",
        "10px": "10px",
        "12px": "12px",
        "13px": "13px",
        "14px": "14px",
        "15px": "15px",
        "18px": "18px",
        "20px": "20px",
        "22px": "22px",
        "25px": "25px",
        "28px": "28px",
        "30px": "30px",
        "32px": "32px",
        "36px": "36px",
        "40px": "40px",
        "50px": "50px",
        "60px": "60px",
        "80px": "80px",
        "100px": "100px",
        "120px": "120px",
        "160px": "160px",
      },
      borderWidth: {
        DEFAULT: "1px",
        0: "0",
        "1px": "1px",
        "2px": "2px",
        "3px": "3px",
        "4px": "4px",
        "6px": "6px",
        "8px": "8px",
        "10px": "10px",
        r: "0 10px 0 0",
      },
      borderRadius: {
        "tl-bl-lg": "1.2rem 0 0 1.2rem",
      },
      letterSpacing: {
        "widest-xl": "0.25em",
        "widest-2xl": "0.5em",
      },
      boxShadow: {
        "right-bottom": "4px 4px 3px rgba(0, 0, 0, 0.4)",
        "right-bottom-heavy": "8px 8px 8px rgba(0, 0, 0, 0.8)",
        "right-bottom-light": "1px 1px 2px rgba(0, 0, 0, 0.2)",
        bottom: "0 4px 8px -2px rgba(0, 0, 0, 0.2)",
      },
      gridTemplateColumns: {
        16: "repeat(16, minmax(0, 1fr))",
        20: "repeat(20, minmax(0, 1fr))",
      },
    },
  },
  plugins: [
    function ({ addUtilities }) {
      addUtilities({
        ".sticky": {
          position: "sticky",
        },
      });
    },
  ],
};
